import { AchievementDefinition } from '../types';

export const ACHIEVEMENTS: Record<string, AchievementDefinition> = {
  first_training: {
    id: 'first_training',
    name: 'First Step',
    description: 'Complete your first training session',
    icon: '🐾',
    condition: 'sessionsCompleted >= 1',
  },
  week_warrior: {
    id: 'week_warrior',
    name: 'Week Warrior',
    description: 'Maintain a 7-day training streak',
    icon: '🔥',
    condition: 'streak >= 7',
  },
  month_master: {
    id: 'month_master',
    name: 'Month Master',
    description: 'Maintain a 30-day training streak',
    icon: '⭐',
    condition: 'streak >= 30',
  },
  command_expert: {
    id: 'command_expert',
    name: 'Command Expert',
    description: 'Master 5 different commands',
    icon: '🎓',
    condition: 'masteredCommands >= 5',
  },
  all_master: {
    id: 'all_master',
    name: 'All Master',
    description: 'Master all basic commands',
    icon: '👑',
    condition: 'allBasicMastered',
  },
  multi_dog: {
    id: 'multi_dog',
    name: 'Pack Leader',
    description: 'Train 3 or more dogs',
    icon: '🐕‍🦺',
    condition: 'dogsCount >= 3',
  },
  hundred_sessions: {
    id: 'hundred_sessions',
    name: 'Centennial',
    description: 'Complete 100 training sessions',
    icon: '💯',
    condition: 'sessionsCompleted >= 100',
  },
  perfect_week: {
    id: 'perfect_week',
    name: 'Perfect Week',
    description: 'Train every day for a week',
    icon: '✨',
    condition: 'perfectWeek',
  },
  speed_runner: {
    id: 'speed_runner',
    name: 'Speed Runner',
    description: 'Complete a training session in 5 minutes',
    icon: '⚡',
    condition: 'sessionMinutes <= 5',
  },
  early_bird: {
    id: 'early_bird',
    name: 'Early Bird',
    description: 'Complete a training session before 9 AM',
    icon: '🌅',
    condition: 'trainingBefore9am',
  },
  night_owl: {
    id: 'night_owl',
    name: 'Night Owl',
    description: 'Complete a training session after 6 PM',
    icon: '🌙',
    condition: 'trainingAfter6pm',
  },
  comeback_kid: {
    id: 'comeback_kid',
    name: 'Comeback Kid',
    description: 'Resume training after 7 days away',
    icon: '🚀',
    condition: 'resumeAfter7days',
  },
  master_trainer: {
    id: 'master_trainer',
    name: 'Master Trainer',
    description: 'Master all commands in a category',
    icon: '🏆',
    condition: 'categoryMastered',
  },
  session_legend: {
    id: 'session_legend',
    name: 'Session Legend',
    description: 'Complete 50 training sessions',
    icon: '🎯',
    condition: 'sessionsCompleted >= 50',
  },
  year_commitment: {
    id: 'year_commitment',
    name: 'Year Commitment',
    description: 'Maintain a 365-day training streak',
    icon: '🎖️',
    condition: 'streak >= 365',
  },
  command_master_basic: {
    id: 'command_master_basic',
    name: 'Basic Master',
    description: 'Master all 5 basic commands',
    icon: '📚',
    condition: 'allBasicMastered',
  },
  command_master_manners: {
    id: 'command_master_manners',
    name: 'Manners Expert',
    description: 'Master all manners commands',
    icon: '🎩',
    condition: 'allMannersMastered',
  },
  command_master_advanced: {
    id: 'command_master_advanced',
    name: 'Advanced Master',
    description: 'Master all advanced commands',
    icon: '💎',
    condition: 'allAdvancedMastered',
  },
  dog_whisperer: {
    id: 'dog_whisperer',
    name: 'Dog Whisperer',
    description: 'Train 5 or more dogs',
    icon: '🐺',
    condition: 'dogsCount >= 5',
  },
  milestone_10: {
    id: 'milestone_10',
    name: 'Double Digits',
    description: 'Complete 10 training sessions',
    icon: '🔟',
    condition: 'sessionsCompleted >= 10',
  },
  milestone_25: {
    id: 'milestone_25',
    name: 'Quarter Century',
    description: 'Complete 25 training sessions',
    icon: '2️⃣5️⃣',
    condition: 'sessionsCompleted >= 25',
  },
  milestone_75: {
    id: 'milestone_75',
    name: 'Three Quarters',
    description: 'Complete 75 training sessions',
    icon: '7️⃣5️⃣',
    condition: 'sessionsCompleted >= 75',
  },
  consistency_hero: {
    id: 'consistency_hero',
    name: 'Consistency Hero',
    description: 'Maintain a 14-day training streak',
    icon: '💪',
    condition: 'streak >= 14',
  },
  weekend_warrior: {
    id: 'weekend_warrior',
    name: 'Weekend Warrior',
    description: 'Complete 5 training sessions in weekends',
    icon: '🏖️',
    condition: 'weekendSessions >= 5',
  },
};
